### ISSUE TITLE
Error while running challenge2_solution.py on python3: dictionary changed size during iteration

### ISSUE THREAD

**Issue by maydaymarina** [mattblefeld/challenge_1#1]
Hi Matt,

Thank you for sending in your Python exercises!

I am reviewing them and when running on Python 3.9,  getting an error on challenge2_solution.py:

**_RuntimeError: dictionary changed size during iteration_**

From what I understand, Python3 has a problem with deletion while iterating through dictionary. 
Could you please take a look and see if this can be addressed? 

Thank you,
Marina Ivanova

**Comment by mattblefeld** [comment]
Hi Marina,

Thank you for catching that. I have spent so much time working in py2 that it was an oversight that my interpreter was set to py2 when developing it. Hence, that's why it worked on my machine. I fixed it by creating a list of the dict and have just made the commit.

Best,
Matt Blefeld
